<?php
declare(strict_types=1);

return [
    'aficiones' => [
        'leer' => [
            'Un libro y un rincón tranquilo y ya tiene la tarde hecha.',
            'Es bastante rata de biblioteca. Lo dice como un cumplido, creo.',
            'Como entre en una librería, se esfuma. El recado espera.',
            'Lee en los huecos: el café, el banco, el minuto antes de que llegue nadie.',
            'Si le preguntas qué anda leyendo, te cuenta el argumento y se le olvida la hora.',
            'Un libro bien elegido le llega más que un ramo. Anótalo.',
            'No presume de lecturas. Luego te enteras por un marcador olvidado.',
        ],
        'escribir' => [
            'Si se queda mirando un cuaderno, no le hables. Está en otra parte.',
            'Escribe. No presume. Luego te enteras por una esquina de papel.',
            'Tiene frases a medias en servilletas. No las tires.',
            'Un rato a solas con un boli le arregla el carácter. O se lo complica. Según la página.',
            'No hace falta publicar: hace falta que salga. El cajón ya verá.',
            'Si pide silencio, a veces es para eso. No para rumiar. Bueno, las dos cosas.',
            'Regalarle un cuaderno bonito es acertar. Preguntar qué escribe, ya es otra guerra.',
        ],
        'comics' => [
            'No es que no lea: lee con dibujitos y se ofende si lo dices así.',
            'Tiene una pila de cómics que defiende como quien defiende a un primo.',
            'Un tomo nuevo le ilumina la semana. El precio, mejor no.',
            'Discute canon con una seriedad de junta de vecinos.',
            'En la tienda va directo a la estantería de viñetas. El resto es decorado.',
            'Prestarle un cómic es un voto de confianza. Devolverlo doblado, un delito menor.',
            'No es nostalgia: es que esas historias le funcionan. Punto.',
        ],
        'cine_sala' => [
            'El cine de verdad, con butaca y palomitas. La pantalla del salón no le sirve.',
            'Si hay sesión, se organiza la semana alrededor. Sin drama. Bueno, un poco.',
            'La cola, la butaca, el anuncio de apagar el móvil. Eso es ir al cine.',
            'Un estreno le pone de un humor que conviene aprovechar.',
            'Comenta la película en la acera. El criterio, discutible; las ganas, no.',
            'Regalar entradas es acertar. Elegir el género sin preguntar, un riesgo.',
            'El sofá está bien para repetir. Para verla de verdad, pide sala.',
        ],
        'ver_en_casa' => [
            'El sofá es su sala vip. No espera que nadie lo entienda.',
            'Mantiene maratones con una seriedad que otros reservan para el trabajo.',
            'Una manta, un mando y que no llamen. El plan del siglo, según quien manda.',
            'Los spoilers le sientan como un empujón en la cola del pan.',
            'Propón una serie y te ganas una tarde. Propón salir a las ocho, ya veremos.',
            'No es que no salga: es que algunas historias piden pijama.',
            'Si se queda hasta las tantas, al día siguiente el café es sagrado.',
        ],
        'videojuegos_cozy' => [
            'Juega a cosas bonitas donde nadie te grita. Lo cuenta como quien habla de punto de cruz.',
            'No es "gamer". Es que le calma plantar tomates digitales. Déjalo.',
            'Se queda hasta tarde construyendo islas. El pueblo no se entera. Mejor.',
            'Un juego suave le baja los hombros. Uno de ranking, al revés.',
            'Si ves la lucecita de la consola, no es momento de recados urgentes.',
            'Regalarle un juego tranquilo es un detalle fino. Uno competitivo, una apuesta.',
            'Habla de cosechas y aldeanos con una ternura rara. Tú verás.',
        ],
        'videojuegos_competitivo' => [
            'Si pierde, la casa se entera. Si gana, también.',
            'Le brilla el ojo cuando hay ranking. Luego dice que es solo un juego.',
            'Una revancha más. Siempre una revancha más. La cena espera.',
            'El auricular es frontera. Cruzarla sin aviso tiene consecuencias.',
            'Ganar le sienta bien. Perder le deja de un humor que pide aire.',
            'Un uno contra uno le enciende. Un paseo, según el día.',
            'No hace falta entender el juego. Hace falta no comentar la jugada a destiempo.',
        ],
        'arcade' => [
            'Las máquinas del arcade le devuelven a los quince años y no pide perdón.',
            'Cambia monedas con una solemnidad de misa.',
            'Un récord local le da para una semana de conversación. Prepárate.',
            'El parpadeo de las pantallas le sienta mejor que un atardecer, algunos días.',
            'Si hay una máquina libre, se le ve el plan en la cara.',
            'No va a "pasar el rato": va a intentar esa pantalla otra vez.',
            'Invitar a una ronda de fichas es un buen plan. Hablar por encima de la partida, no.',
        ],
        'juegos_mesa' => [
            'Si saca una caja, la sobremesa se alarga. Avisa a quien tenga que madrugar.',
            'Explica reglas con paciencia. La primera vez. La segunda, ya veremos.',
            'Una partida le arregla un domingo. Una pelea por las reglas, también, a su manera.',
            'Colecciona cajas como quien colecciona primos: con nombres y manías.',
            'Si el plan es "un juego corto", cuenta dos horas. Mínimo.',
            'Le gusta la mesa, no el móvil. El tablero pide manos y cara.',
            'Regalar una caja nueva es acertar. Abrirla sin leer el reglamento, un riesgo calculado.',
        ],
        'bingo' => [
            'El bingo no es un chiste. Es una cita con el destino y un rotulador.',
            'Los martes tiene un compromiso. No preguntes si es con una persona.',
            'Un cartón casi lleno le pone el pulso en la garganta. El pueblo lo ha visto.',
            'Llega pronto. Elige sitio. Nadie toca el boli ajeno.',
            'Gane o no, sale hablando del último número como de un primo lejano.',
            'Si cancelan el bingo, el humor se resiente. Es información útil.',
            'Acompañar vale. Hablar durante el canto, ya es otra afición que no tiene.',
        ],
        'escuchar_musica' => [
            'Anda con banda sonora. Si se la quitas, se queda a medias.',
            'No hace falta que cante: con que suene, ya está en su sitio.',
            'Los auriculares no son un capricho. Son una pared educada.',
            'Te recomienda una canción y luego pregunta qué te ha parecido. Contesta en serio.',
            'Un disco nuevo le cambia el paso. Se le nota en cómo cierra la puerta.',
            'No implica bailar ni karaoke. A veces solo implica mirar por la ventana.',
            'Si suena algo bueno, se calla. Eso, aquí, es un cumplido.',
        ],
        'tocar_instrumento' => [
            'Tiene un instrumento y una relación seria. El vecindario lo confirma.',
            'Si pide un rato a solas, suele ser para eso. No para rumiar. Bueno, las dos cosas.',
            'Ensaya. Se le oye. El pueblo ha hecho las paces con eso, más o menos.',
            'Un jam improvisado le saca de quicio o le ilumina. Según si estaba listo.',
            'Habla de cuerdas y de afinación como otros hablan del tiempo.',
            'Regalar cuerdas, partituras, un rato de silencio: aciertas. Un micro por sorpresa, no.',
            'No siempre quiere público. A veces quiere que la pieza salga, y ya.',
        ],
        'conciertos' => [
            'Prefiere la música con gente cerca y un escenario pequeño.',
            'Un bolo en el bar le arregla una semana entera. O se la fastidia, según el sonido.',
            'Llega tarde por la cola y no se queja. Forma parte del rito.',
            'Si hay música en directo, el resto de planes se reorganiza solo.',
            'Sale del concierto hablando del bajo, no de quién estaba. Prioridades.',
            'Un escenario pequeño le vale más que un recinto enorme. El oído, no el aforo.',
            'Invitar a un bolo local es un buen plan. Hablar encima de la canción, un error.',
        ],
        'karaoke' => [
            'En el karaoke se le olvida el resto. Incluido el pudor, a veces.',
            'No canta bien. Canta como si le fuera el alquiler. Es peor y mejor.',
            'Tiene un tema fetiche. El pueblo lo sabe. Fingir sorpresa ya no cuela.',
            'Un dueto inesperado le puede el carácter. O lo rompe. Según la noche.',
            'No hace falta cantar afinado. Hace falta cantar como si importara.',
            'Si hay micro abierto, se le ve el debate interno. Suele ganar el micro.',
            'Sacar a cantar funciona. Obligar, no. El matiz es todo.',
        ],
        'correr' => [
            'Sale a correr como quien paga una deuda con su cabeza.',
            'Si amanece y no ha salido, el día le sale torcido. Aviso a navegantes.',
            'Habla de kilómetros con una modestia falsa. Se le ve el orgullo en el paso.',
            'Quedar a correr es un plan. Quedar a charlar mientras corre, otro, más difícil.',
            'Una lesión leve le pone de un humor bajo. El cuerpo manda, y se le resiste.',
            'El parque a primera hora es territorio. El banco, para después.',
            'No es exhibición: es que si no sale, la cabeza no cierra.',
        ],
        'bici' => [
            'La bici no es un medio: es una personalidad con ruedas.',
            'Habla de puertos y de viento como otros hablan de series.',
            'Un pinchazo le parece un drama menor y un relato mayor.',
            'Si hay quedada, aparece con casco y opinión. Las dos cosas pesan.',
            'El pueblo llano le sabe a poco. Una cuesta le mejora el día.',
            'Regalar un trapo de cadena o un mapa es más fino de lo que parece.',
            'No va a "dar una vuelta": va a hacer la ruta. Distinto.',
        ],
        'deporte_equipo' => [
            'Necesita un balón y otras cuatro personas. El sofá no le sustituye.',
            'Gana, pierde, pero sobre todo discute el fuera de juego hasta la cena.',
            'Un partido del pueblo le organiza el domingo. El resto es relleno.',
            'La afición no es verlo: es estar en el campo, aunque duela la rodilla.',
            'Si falta gente, llama. Si sobra, discute el once. Siempre hay once.',
            'Una derrota le deja sin hablar un rato. Luego vuelve con la revancha en la boca.',
            'Apuntarse al equipo es un sí. Ir de público a abuchear, ya es otra persona.',
        ],
        'gimnasio' => [
            'El gimnasio le cuadra. Las pesas no le deben nada y se lo agradece.',
            'Tiene una hora sagrada entre máquinas. Celestine, no la pises sin motivo.',
            'Sale de allí de mejor humor. O de ninguno, que a veces es lo mismo.',
            'Habla de series y descansos con una seriedad de receta médica.',
            'Se puede ser de deporte y odiar este sitio. Esta persona, al revés: el sitio le va.',
            'Un plan de pesas le vale. Un plan de copas justo después, según las piernas.',
            'No va a verse. Va a que el cuerpo haga lo que tiene que hacer.',
        ],
        'baile' => [
            'Baila. No "le gusta la música": se le va el cuerpo solo.',
            'En la pista se le entiende mejor que en una sobremesa.',
            'Una clase de baile le sienta como un café bien puesto.',
            'Si suena algo bueno, ya está en pie. El corro, que se aparte.',
            'No espera a que le saquen. Sale. Luego, si acaso, invita.',
            'La discoteca le sirve si hay pista. Si solo hay gritos, se queda en la barra.',
            'Sacar a bailar suele funcionar. Obligar a una coreografía, ya es otro recado.',
        ],
        'yoga' => [
            'Estira, respira y pide que no le conviertan eso en chiste de incienso.',
            'No es que sea zen. Es que si no se mueve despacio, explota.',
            'La esterilla es territorio. El móvil, fuera. El cotilleo, después.',
            'Una clase suave le baja el volumen al día. Se le nota a la salida.',
            'Habla de caderas y de respiración sin pedir permiso. Tú decides si te quedas.',
            'El spa, el parque, un rincón en casa: el sitio importa menos que el rato.',
            'No va a "relajarse" de postal. Va a que el cuerpo deje de estar en guardia.',
        ],
        'pasear' => [
            'Un paseo le arregla más que un consejo. Y sale más barato.',
            'Camina para pensar. Si le acompañas, no hace falta rellenar el silencio.',
            'Conoce atajos que el pueblo usa sin saber que son atajos.',
            'Una vuelta al parque le pone en su sitio. Dos, si el día viene torcido.',
            'Quedar a pasear es un plan de verdad. No es "no se nos ocurre otra cosa".',
            'Habla mejor andando que a la mesa. El banco, para el descanso.',
            'Si el plan es largo, lleva calzado decente. El resto se improvisa.',
        ],
        'senderismo' => [
            'Si hay cuesta, se anima. El pueblo llano le sabe a poco.',
            'Habla de botas con el respeto que otros reservan a los zapatos de boda.',
            'Un domingo de ruta le limpia la cabeza. El lunes se le nota.',
            'El blister es anécdota. La vista, el premio. El bocadillo, sagrado.',
            'Propón una senda y tienes plan. Propón el sofá el mismo día, negociad.',
            'No es una carrera. Es ir, llegar, mirar, volver. En ese orden.',
            'Avisa si hay desnivel. Esta persona cuenta con la cuesta. El resto, a veces no.',
        ],
        'plantas' => [
            'Habla con las plantas. No es metáfora. O sí, pero da igual: tiran.',
            'Si se le muere un geranio, hay duelo. Bajo, pero hay duelo.',
            'Un esqueje le parece un buen regalo. Un ramo cortado, según el día.',
            'Sabe de riegos y de sombras. Pregunta y te quedas un rato.',
            'El parque le vale para mirar hojas. La tienda, si hay macetas, también.',
            'Tiene nombres para las plantas. No siempre para las personas nuevas.',
            'Regalar una planta es acertar. Olvidar el riego, un delito menor.',
        ],
        'perros' => [
            'Los perros ajenos ya son un poco suyos. Quien pasea tarda en enterarse.',
            'Si hay un hocico en el parque, la conversación se resuelve sola.',
            'Se agacha sin pedir permiso. El perro, de acuerdo. Quien lleva la correa, a veces no.',
            'Un paseo canino le organiza la tarde mejor que una agenda.',
            'Habla de caracteres de perro con más tino que de los de la gente. Casi.',
            'Si hay un animal cerca, se le ve el humor antes. Es un dato útil.',
            'No hace falta tener perro. Hace falta que haya uno, y ya está el plan.',
        ],
        'picnic' => [
            'El mantel en el césped es su idea de lujo. Hormigas incluidas.',
            'Organiza comidas al aire con una logística de boda pequeña.',
            'El tupper es política. El plástico de un solo uso, una opinión.',
            'Las avispas forman parte del folclore. Se queja y sigue.',
            'Un picnic le sabe a domingo aunque sea jueves.',
            'Si el plan es césped y comida, aparece. Si es cola para un banco, ya veremos.',
            'Aporta siempre algo. Quien no aporta, se nota. No es rencor: es inventario.',
        ],
        'mirador' => [
            'Se sube al mirador a mirar. Punto. No todo atardecer es una declaración.',
            'Le sienta bien el pueblo visto de lejos. A veces también la gente.',
            'Un rato arriba le calla la cabeza. El silencio, si se comparte, vale igual.',
            'No pide violín. Pide cielo y que no hablen encima de la luz.',
            'Fotografiar, sí. Convertir el sitio en postal de anuncio, no hace falta.',
            'Quedar en el mirador es un plan sencillo. Vestirlo de cine, ya es otro recado.',
            'Baja distinto. Se le nota en cómo saluda en la cuesta.',
        ],
        'cocina' => [
            'Cocina de verdad. Si te invita, ve. Si dices que da igual, se ofende.',
            'Prueba recetas con una fe que otros reservan para las quinielas.',
            'La cocina es territorio. Entrar a "ayudar" sin que te lo pidan tiene riesgo.',
            'Un cacharro nuevo le ilumina más que un ramo. Prioridades.',
            'Si hay olla, hay plan. El restaurante, otro día, o nunca.',
            'Cuenta la receta como quien cuenta un viaje. Tú decides si tomas notas.',
            'Regalar un ingrediente difícil es fino. Decir "mejor pedimos", menos.',
        ],
        'restaurantes' => [
            'Le encanta que le pongan la mesa. Cocinar está bien; que le cocinen, también.',
            'Elige restaurante como quien elige película: con veto incluido.',
            'Una reserva le sienta como un traje bien cortado. De vez en cuando.',
            'Tiene un plato fetiche. Si no está, el local baja enteros.',
            'Salir a comer le parece un plan, no un trámite. El matiz importa.',
            'Comenta la carta con una seriedad que otros reservan al tiempo.',
            'Invitar a un sitio "en condiciones" acierta. Improvisar una hamburguesa de gasolinera, no.',
        ],
        'cafe_con_gente' => [
            'La cafetería es su despacho. El café, una excusa bastante convincente.',
            'Si dice "un café", cuenta una hora. Mínimo.',
            'Tiene mesa de siempre. Quien la ocupa, peca sin saberlo.',
            'El café se enfría de tanto hablar. Es un oficio, no un descuido.',
            'Quedar a tomar algo es el plan por defecto. Y funciona.',
            'No hace falta un motivo. El motivo es la mesa y quien se siente.',
            'Si cancelas el café, se nota. No es drama: es que era el hueco de la semana.',
        ],
        'merendar' => [
            'Defiende la merienda como institución. Con razón.',
            'Un dulce a media tarde le pone de un humor que conviene aprovechar.',
            'La pastelería no es un recado: es una cita.',
            'Si hay tarta, hay trato. Si no hay tarta, hay negociación.',
            'Merendar en el picnic le parece civilización. Merendar de pie, un apaño.',
            'Sabe qué día sale el hojaldre bueno. Eso es información sensible.',
            'Invitar a merendar acierta casi siempre. Saltarla "porque luego cenamos", casi nunca.',
        ],
        'manualidades' => [
            'Hace cosas con las manos y luego finge que no es para regalarlas. Lo es.',
            'Si hay taller, aparece. Si no hay taller, se lo inventa en la mesa de la cocina.',
            'Un rato de tijeras y pegamento le baja el volumen al día.',
            'Regala lo que hace. Recibir un "qué bonito" le dura. Un "para qué sirve", también.',
            'La mesa acaba llena de recortes. Forma parte del proceso. El orden, después.',
            'Habla de materiales con entusiasmo de feria. Tú verás si te apuntas.',
            'Un kit sencillo es un buen regalo. Decir que es cosa de críos, un error.',
        ],
        'costura' => [
            'Cose. Arregla. Opina de dobladillos con autoridad moral.',
            'Un botón suelto le pica más que un rumor.',
            'Una tela bonita le ilumina el paso por la tienda. El resto puede esperar.',
            'Hace favores de aguja. Luego hay que devolverlos, aunque sea en café.',
            'El arreglo bien hecho le parece respeto. Tirar la prenda, un desperdicio.',
            'Habla de puntadas como otros de series. El hilo tiene temporada.',
            'Llevar algo roto es un plan. Llevarlo a última hora, un abuso leve.',
        ],
        'bricolaje' => [
            'Si algo se mueve y no debería, ya está buscando el destornillador.',
            'Ayuda. A veces sin que se lo pidan. A veces sin que haga falta. El resultado varía.',
            'Una estantería bien puesta le da una paz que otros logran con spa.',
            'El dedo golpeado es anécdota. El tornillo torcido, una ofensa.',
            'Tiene un cajón de herramientas y una opinión sobre cada una.',
            'Pedir un apaño funciona. Vigilar el apaño, según el día.',
            'Regalar una herramienta decente acierta. Un mueble "fácil de montar", una broma.',
        ],
        'fotografia' => [
            'Para el paso para una foto y el pueblo entero espera, resignado.',
            'No hace selfies. Hace "espera, la luz". Es peor.',
            'Un atardecer le pone el pulso en el disparador. El resto, que espere.',
            'Guarda álbumes. No presume. Luego te los enseña y se te va la tarde.',
            'Una foto robada (de las buenas) le parece un tesoro. Una posada a la fuerza, no.',
            'El mirador, el parque, una esquina rara: el sitio es la luz, no el monumento.',
            'Regalar un carrete o una copia en papel es fino. Pedir que borre una, delicado.',
        ],
        'coleccionismo' => [
            'Colecciona algo concreto y puede explicarlo veinte minutos. Tú verás.',
            'Un hallazgo en la tienda le ilumina la semana. No preguntes el precio.',
            'La vitrina no es vanidad: es archivo. Tocar sin permiso, delito.',
            'Trueque, feria, cajón de alguien: huele la pieza rara a distancia.',
            'Habla de ediciones y de faltas como quien habla de familia.',
            'Regalar "la" pieza es acertar en grande. Regalar "una parecida", un riesgo.',
            'No compra por comprar. Busca. Cuando aparece, se le ve en el paso.',
        ],
        'moda' => [
            'La tienda no es solo ropa: es teatro. Mira, toca, opina, a veces compra.',
            'Se le ve el humor en el peinado. Y en si ha pasado o no por los aparadores.',
            'Un escaparate bueno le detiene. Un pasillo de ofertas, según el día.',
            'Prueba, aconseja, descarta. Quien va de recadero se aburre. Quien opina, no.',
            'No es consumo a lo loco: es que le gusta ver cómo queda el mundo puesto.',
            'Libros, objetos, una bufanda rara: el hallazgo importa más que la etiqueta.',
            'Ir de tiendas juntos funciona si hay café después. Sin café, es expedición.',
        ],
        'copas' => [
            'Una copa le suelta la lengua. Dos, la agenda. Tres, ya es El Cotilleo quien informa.',
            'El bar le sienta bien. No lo confundas con ganas de discoteca.',
            'Una ronda a tiempo abre conversaciones que el café deja a medias.',
            'La barra es confesionario. Lo que se dice, a veces, se queda ahí. A veces no.',
            'Si hay sitio en la barra, aparece. Si hay cola de discoteca, ya es otro humor.',
            'No bebe para olvidar. Bebe para que el día termine en voz baja, o en voz alta.',
            'Invitar a una copa es un plan. Convertirlo en noche eterna, según.',
        ],
        'fiesta' => [
            'Cuando hay fiesta, aparece. Cuando no hay, a veces la monta.',
            'La noche le mejora el carácter. A algunos les pasa lo contrario, aviso.',
            'Sabe dónde está el corro bueno. El resto del local es decorado.',
            'Un amanecer contado al día siguiente forma parte del relato. El dolor de cabeza, también.',
            'No necesita un motivo grande. Con que haya gente y un poco de ruido, tira.',
            'Si cancelan la noche, se reorganiza. Suele reorganizar hacia otro sitio con gente.',
            'Apuntarse a salir funciona. Prometer irse "solo un rato", una negociación.',
        ],
        'spa' => [
            'El spa no es capricho: es mantenimiento. Como el coche, pero con albornoz.',
            'Si el día ha sido largo, no pide un plan: pide agua caliente y que no le molesten.',
            'El albornoz le sienta mejor que un traje. No lo discute.',
            'Un circuito de agua le baja los hombros. Se le ve. Literal.',
            'Regalar un bono es acertar. Un plan ruidoso el mismo día, no.',
            'Pide silencio y toalla. El cotilleo, a la salida. Si acaso.',
            'No va a posar. Va a que el cuerpo deje de protestar un rato.',
        ],
        'asociacion' => [
            'Se apunta a lo del pueblo. Fiestas, listas, lo que se tercie. Alguien tiene que hacerlo.',
            'Sabe quién organiza qué. Es información sensible. Trátala como tal.',
            'Una comisión le parece normal. A otras personas les parece un castigo.',
            'El cartel de las fiestas le importa. El color, el verbo, quién queda fuera.',
            'Si hay que montar sillas, está. Si hay que opinar, también. Sobre todo lo segundo.',
            'El bingo, la cafetería, el local social: son despachos, no ocio puro.',
            'Pedir un favor de pueblo funciona. Pedirlo a última hora, menos.',
        ],
        'crucigramas' => [
            'Hace crucigramas como quien entrena para no morder a nadie.',
            'Si se atasca en una definición, el café se enfría. Prioridades.',
            'El periódico no es noticia: es el 7 horizontal.',
            'Pedir ayuda es un honor. Decir la palabra sin que la pidan, una descortesía.',
            'Un rato de pasatiempos le deja de mejor humor que un consejo.',
            'La biblioteca y la cafetería le valen igual: mesa, boli, silencio a ratos.',
            'Regalar un libro de crucigramas es fino. Hacerlos por encima, un delito menor.',
        ],
        'tertulia' => [
            'Le gusta hablar. De verdad. No el ruido: el hilo.',
            'Si la conversación está buena, se le olvida la hora. Y a veces la mesa de al lado.',
            'Una mesa sin reserva y un tema vivo: eso es plan.',
            'Debate con ganas y sin prisa. Quien quiera zanjas rápidas, que se siente aparte.',
            'El bar y la cafetería le sirven de foro. El sofá, solo si hay gente.',
            'No cotillea por cotillear: sigue el hilo. El chisme, si aparece, es combustible.',
            'Quedar a hablar funciona. Quedar a "estar" sin tema, se le hace cuesta.',
        ],
    ],
    'rasgos' => [
        'directo' => [
            'Va al grano. El rodeito le parece una pérdida de tarde.',
            'Si hay que decirlo, lo dice. El resto es decorado.',
            'Una pregunta clara le sienta bien. Una insinuación, le cansa.',
            'No adorna el no. Tampoco el sí. Conveniente y, a veces, seco.',
            'Si te riza el rizo, se le ve la impaciencia en la ceja.',
            'Celestine: no hace falta preparar el discurso. Hace falta la frase.',
            'Quien espera diplomacia de manual, se sorprende. Quien quiere la verdad, agradece.',
        ],
        'timido' => [
            'Le cuesta el primer paso. El segundo, a veces, lo da de una vez.',
            'No es que no quiera: es que la entrada le sale cara. Luego puede cantar karaoke, ojo.',
            'En una mesa nueva se queda a media frase. No es desinterés: está tomando tierra.',
            'Si le dejas el hueco, aparece. Si le empujas, se retrasa una semana.',
            'Habla más cuando no hay un corro mirando. El corro, luego, a lo mejor se apunta.',
            'El silencio inicial no es un no. Es un calentamiento. Celestine, cuenta hasta tres.',
            'Quien espera un poco, se lleva conversación. Quien apremia, se lleva un "otro día".',
        ],
        'reservado' => [
            'Cuenta poco. No es vacío: es selección.',
            'Si te suelta algo personal, anótalo. No lo repite cada martes.',
            'Las preguntas de relleno le cansan. Las justas, las aguanta.',
            'Hay un cajón cerrado. No es un reto. Es un cajón.',
            'En el cotilleo escucha más de lo que aporta. El pueblo lo nota tarde.',
            'Un plan íntimo le va. Un plan de confesiones en grupo, menos.',
            'No es hielo: ahorra. El calor, cuando sale, calienta de verdad.',
        ],
        'observador' => [
            'Se entera de más de lo que habla. Incómodo para quien cotillea alto.',
            'Mira. Luego opina, si acaso. El orden importa.',
            'Un detalle de pasada le dura. El peinado nuevo, el tono raro, la silla cambiada.',
            'Quien miente en la mesa tiene un problema. No siempre lo dice. Lo guarda.',
            'En el bar parece ausente. Está tomando nota. Distinto.',
            'Un "¿te has dado cuenta?" le sienta como un café. Suele haber visto eso, sí.',
            'No es magia: es que mira cuando el resto habla.',
        ],
        'sociable' => [
            'La gente le sienta bien. No todas las pistas ni todos los volúmenes.',
            'Necesita caras. Luego puede odiar la discoteca igual. Las dos cosas caben.',
            'Se apunta. La mesa extra rara vez es un problema.',
            'Un día sin nadie le deja fuera de sitio. No es tristeza: es que faltan caras.',
            'Saluda en la calle de verdad. No es educación: es que le gusta el roce.',
            'Un plan de dos le vale. Un plan de ocho, también. El sofá a solas, a ratos.',
            'No implica fiesta. Implica gente. El sitio, ya se habla.',
        ],
        'cotilla' => [
            'Se entera. A veces incluso de lo que aún no ha pasado.',
            'El pueblo es su serial. No siempre lo cuenta. Eso ya es ética, o estrategia.',
            'Una noticia pequeña le abre el día. Una grande, la semana.',
            'Pregunta con tiento. O sin tiento. Según cómo venga el café.',
            'Sabe el nombre del primo y el motivo del silencio. Útil y delicado.',
            'Si dices "no se lo digas a nadie", hay un debate interno. Suele ganar el secreto. Suele.',
            'No es oficio sucio: es que le gusta estar al tanto. El reparo, si hay, se nota en lo que no suelta.',
        ],
        'discreto' => [
            'No reparte lo que sabe. En este pueblo eso casi es un superpoder.',
            'Si le cuentas algo, se queda ahí. Raro. Valioso.',
            'El cotilleo le llega y no sigue viaje. Quien habla alto se confunde.',
            'Una confianza le pesa bien. Una filtración le pesa mal. Muy mal.',
            'En la tertulia escucha. Aporta poco de lo ajeno. Aporta lo suyo, si toca.',
            'Pedir un secreto es razonable. Pedir que lo confirme en voz alta, no.',
            'Celestine: lo que se diga aquí no sale por el bingo. Casi nunca sale.',
        ],
        'ironico' => [
            'El tono va por otro lado. Si lo tomas al pie de la letra, os peleáis sin motivo.',
            'Bromea en serio. O habla en broma. Adivina.',
            'Una frase seca puede ser cariño. Una dulce, aviso. El manual no existe.',
            'Se le ve la ceja. Eso es el subtítulo. Apréndetelo.',
            'Quien necesita todo explícito, sufre. Quien pilló el tono, se queda.',
            'En un malentendido de ironía, cede tarde. Cree que se entendía.',
            'No es crueldad: es distancia. A veces ayuda. A veces deja a alguien en el aire.',
        ],
        'bromista' => [
            'Suelta chistes como quien suelta aire. Algunos salen bien.',
            'Si el ambiente se pone denso, tira de broma. A veces ayuda. A veces no.',
            'Una pulla a tiempo le parece un favor. A destiempo, un problema.',
            'Se ríe de lo propio antes. Eso desarma. O cansa. Según la racha.',
            'En un plan serio se le ve el esfuerzo por no soltarla. A veces gana el chiste.',
            'No hace falta palco: hace falta un oído. El resto es ganas.',
            'Si la broma duele, se le puede decir. Suele recoger. Suele.',
        ],
        'socarron' => [
            'Picarda de pueblo. No es crueldad: es deporte local.',
            'Te pincha para ver si aguantas. Si aguantas, sois de los suyos. Si no, también, pero más lejos.',
            'Una pulla bien puesta le parece educación. El piropo fácil, no.',
            'En el bar se le entiende mejor. En una mesa formal, hay que traducir.',
            'No adula. Comenta. El comentario suele tener filo y fondo.',
            'Quien se ofende a la primera, lo tiene crudo. Quien devuelve la pulla, entra.',
            'Celestine: si te pica, a veces es que le caes bien. A veces, no. Mira el resto.',
        ],
        'leal' => [
            'Cuando está, está. No es ruido: es sitio.',
            'No cambia de gente como de chaqueta. Quien está dentro, lo nota.',
            'Un apuro ajeno le mueve. Un cotilleo contra los suyos, le cierra.',
            'Acude. Aunque el plan sea malo. Aunque la hora sea peor.',
            'La constancia no la anuncia. Se ve en las semanas, no en un brindis.',
            'Pedir ayuda es razonable. Dudar de si va a venir, menos.',
            'Si hay que elegir bando, elige tarde y se queda. El resto es conversación.',
        ],
        'empatico' => [
            'Se le pegan los estados ajenos. Conveniente y cansino.',
            'Se da cuenta de cómo estás antes de que lo cuentes. Inquietante, útil.',
            'Un mal gesto en la mesa le deja raro el resto del café.',
            'Consuela de verdad. No de manual. A veces se queda sin pila.',
            'Las películas tristes le llegan. Las noticias del pueblo, también.',
            'Si alguien está mal, el plan se reorganiza. Sin anuncio. Se nota.',
            'Celestine: no hace falta fingir alegría. Se pilla. Mejor el tono cierto.',
        ],
        'cabezota' => [
            'Cuando se planta, se planta. El resto es negociación de fachada.',
            'No es que no oiga: es que ya decidió. Matiz importante.',
            'Una discusión larga le cansa menos que ceder por ceder.',
            'Si el plan era A, B tiene que merecer la pena. De verdad.',
            'Pedir un cambio a última hora pone de mal humor. Avisa antes.',
            'Tiene razón a menudo. Cuando no, cuesta. El pueblo lo sabe.',
            'No hace falta gritar. Hace falta un argumento que no haya oído diez veces.',
        ],
        'protector' => [
            'Se pone delante. A veces hace falta. A veces ahoga. El arte está en el cuándo.',
            'Cuida. Pregunta si la otra persona quería ser cuidada.',
            'Un apuro ajeno le saca de la silla. Un consejo no pedido, también.',
            'Vigila el camino a casa, la copa de más, el rumor feo. Se le ve el radar.',
            'Quien pide espacio a veces se encuentra un escudo. Hay que decirlo claro.',
            'No es mando: es miedo a que pase algo. Traduce eso, no el tono.',
            'Celestine: si te cubre de más, se puede hablar. Suele recoger si no es ataque.',
        ],
        'independiente' => [
            'Se basta. No es un rechazo: es un sistema operativo.',
            'Pide poco. Cuando pide, es que importa.',
            'Un plan en solitario le parece normal. A otras personas les parece aviso.',
            'No necesita compañía para el cine, el paseo, la cena. La admite. Distinto.',
            'Quien se pega, cansa. Quien aparece y se va, encaja.',
            'Compatible con cariño. El hueco, también. Las dos cosas caben.',
            'Ofrecer ayuda vale. Insistir cuando ha dicho que no, menos.',
        ],
        'generoso' => [
            'Da. Tiempo, favores, postre. Luego hay que vigilar que no se quede a cero.',
            'Invita. A veces antes de saber si te apetecía. El gesto es bueno; el radar, mejorable.',
            'Un detalle pequeño le sale solo. Uno grande, también, si el día tira.',
            'Le cuesta recibir. Le resulta más fácil el otro sentido.',
            'Si hay que pagar, ya está buscando el bolsillo. Frenar eso es un arte.',
            'La generosidad no es teatrillo. Se nota cuando nadie mira.',
            'Pedir es difícil. Aceptar, también. El "gracias" hay que decirlo igual.',
        ],
        'vanidoso' => [
            'Le importa cómo queda. No lo niegues: se le ve el esfuerzo.',
            'Un cumplido le dura. Una pega, también. Maneja ambos con tiento.',
            'El espejo no es vicio: es control de daños. El pueblo tiene ojos.',
            'Una foto borrosa le pica más que un rumor pequeño.',
            'Se arregla para el bar igual que para una boda. El listón es suyo.',
            'No hace falta adular. Hace falta no ignorar que se ha esforzado.',
            'Un "vas bien" a tiempo abre puertas. Un "da igual cómo vas", las cierra un poco.',
        ],
        'orgulloso' => [
            'Pedir perdón le sale caro. No imposible: caro.',
            'Prefiere tener razón a tener paz. Trabajo para Celestine, si te pica.',
            'Una humillación chica le dura. Una grande, se queda en el cuerpo.',
            'Ceder en público cuesta más que ceder en la cocina. Elige el sitio.',
            'No pide ayuda hasta tarde. Cuando pide, el asunto ya pesa.',
            'Un "tenías razón" le desarma más que un discurso.',
            'No es teatro: es que bajar la guardia le parece un riesgo. Dale tiempo.',
        ],
        'ansioso' => [
            'Adelanta problemas que aún no han aparcado. El cuerpo va por delante.',
            'Si no llega un mensaje, se inventa tres películas. Ninguna es buena.',
            'Esperar le sienta mal. Avisar, bien. El silencio, mal del todo.',
            'Un plan vago le deja en vilo. Un plan escrito, le baja el pulso.',
            'Se le ve en el vaso, en la silla, en la pregunta de más.',
            'No hace falta decir "tranquilo". Hace falta un dato. La hora, el sitio, el sí.',
            'Celestine: un "estoy en camino" vale más que un discurso de calma.',
        ],
        'calido' => [
            'Calienta el cuarto. No es azúcar: es presencia.',
            'Se está bien al lado. Luego puede pedir espacio igual. Cabe.',
            'Un abrazo a tiempo le sale. Uno a destiempo, también, y hay que frenarlo con tiento.',
            'Recuerda el café, el nombre del perro, el mal día de la semana pasada.',
            'En una mesa fría hace de estufa. Se le agradece. A veces se le carga el muerto.',
            'No es calor de cartel. Es que no deja a la gente a la intemperie.',
            'Quien necesita calor, lo encuentra. Quien necesita aire, tiene que pedirlo. Suele entenderlo.',
        ],
        'desconfiado' => [
            'No compra la primera versión. Ni la segunda, según el día.',
            'La gente nueva le parece un tráiler. El filme, más adelante.',
            'Un favor de entrada le pone en guardia. Uno después de tiempo, le entra.',
            'Las promesas grandes le cansan. Las pequeñas cumplidas, le abren.',
            'En el pueblo ha visto demasiado. El escepticismo no es pose.',
            'Ganarse un sí lleva semanas. Perderlo, una tarde. El recuento es justo, a su modo.',
            'No hace falta jurar. Hace falta aparecer cuando se dijo. Punto.',
        ],
        'sensible' => [
            'Le llega todo un poco más alto. No es fragilidad: es volumen.',
            'Una frase de pasada le dura la tarde. Elige las tuyas.',
            'El cine, la música, un mal gesto: entra. No siempre avisa.',
            'Una pulla de broma puede dejar marca. El bromista no siempre lo sabe.',
            'Se le humedece el ojo y sigue. No hace falta un pañuelo de teatro.',
            'Cuidar el tono no es tratar con cristal. Es que el cristal oye.',
            'Si algo duele, a veces lo dice tarde. El retraso no es teatro: es digestión.',
        ],
        'practico' => [
            'Va a lo que funciona. La teoría, si acaso, de postre.',
            'Si el plan no se puede hacer, lo dice. Sin poesía. Gracias.',
            'Un atajo le parece inteligencia. Un rodeíto estético, pérdida.',
            'Pregunta hora, sitio, quién paga. No es sequedad: es que quiere ir.',
            'Las crisis de mantel le cansan. Un problema con solución, le enciende.',
            'Regalar algo útil acierta. Regalar un símbolo vago, según el día.',
            'Celestine: no hace falta el discurso. Hace falta que el plan cierre.',
        ],
        'curioso' => [
            'Pregunta. Se mete. Quiere saber cómo va la cosa por dentro.',
            'Un dato nuevo le alegra el día más que un pastel. Casi.',
            'La pregunta incómoda sale. No siempre en el momento fino.',
            'Un taller, un detrás de cámaras, una receta: se apunta.',
            'El "no se pregunta eso" le parece un cartel. A veces lo respeta. A veces no.',
            'En la biblioteca no solo lee: husmea lomos. En el pueblo, igual.',
            'Contar algo raro es un buen regalo. Contar un secreto ajeno, ya es otra guerra.',
        ],
        'soñador' => [
            'Se va. Vuelve. A veces trae un plan imposible y un brillo raro.',
            'La realidad le parece un primer borrador. Hay que quererle así.',
            'Una idea grande le ocupa la sobremesa. El ticket del pan, a veces no.',
            'Mira el mirador y ya está en otra ciudad. El cuerpo, aquí.',
            'No es que no pise suelo: es que el suelo le sabe a poco algunos días.',
            'Un plan poético le enciende. Uno solo práctico, le deja a medias.',
            'Aterrizar la idea es un favor. Reírse de la idea, un corte.',
        ],
        'constante' => [
            'Mantiene. Lo de cada martes, lo de cada planta, lo de cada persona.',
            'No presume de disciplina. Simplemente no deja que se caiga.',
            'Una racha le sienta bien. Un salto de humor ajeno, le descoloca.',
            'Si dice que va, va. El pueblo usa eso como reloj.',
            'Los planes nuevos entran despacio. Los viejos, tienen silla.',
            'Cancelar a última hora le pica. Avisa con tiempo y hay margen.',
            'No es aburrimiento: es que le gusta que las cosas sigan estando.',
        ],
        'impaciente' => [
            'Lo quiere ya. Esperar le parece un deporte ajeno.',
            'Si el plan tarda, se le pone cara de bus perdido.',
            'Las colas le sientan mal. Las explicaciones largas, también.',
            'Un "en cinco minutos" de verdad le vale. Uno eterno, le cierra el carácter.',
            'Anda rápido. Habla rápido. El resto del pueblo, a veces, no.',
            'Decidir ya le alivia. Dejarlo para el jueves, le deja en vilo.',
            'Celestine: si vas a llegar tarde, dilo. El silencio hincha la espera.',
        ],
        'competitivo' => [
            'Todo le sabe un poco a partido. Hasta un café, si se descuida.',
            'Ganar le sienta bien. Perder, ya es otro rasgo o una manía. No lo mezcles todavía.',
            'Un marcador le pone en modo serio. Luego dice que era broma.',
            'Un reto le enciende. Un "da igual quién gane", le apaga un poco.',
            'En el bingo, en el arcade, en la cocina: hay un palmarés invisible.',
            'La revancha es un lenguaje. Quien no lo habla, se extraña.',
            'No hace falta competir siempre. Hace falta no fingir que no le importa cuando sí.',
        ],
        'perezoso' => [
            'Economiza movimiento. No es que no quiera: es que el sofá hace campaña.',
            'Se apunta… y luego negocia la hora. Suele ganar el sofá. Salvo karaoke. Pasa.',
            'Un plan cerca le vale. Uno que pida dos autobuses, ya es épica.',
            'La mañana le cuesta. La tarde, según. La noche del sofá, fácil.',
            'Quedar para luego es su idioma. Quedar ahora, una negociación.',
            'No es desinterés: es que el esfuerzo quiere motivo. El motivo, a veces, es un dulce.',
            'Empujar con cariño funciona. Empujar con culpa, cierra la persiana.',
        ],
        'tranquilo' => [
            'No se altera a la primera. Ni a la segunda. A la tercera, ya veremos.',
            'Baja el volumen de la mesa sin decir nada. Útil. A veces desesperante.',
            'Un "no pasa nada" le sale de verdad. A quien está en llamas, le puede irritar.',
            'El caos ajeno le rodea y sigue. Hasta que no puede. Entonces, poco teatro.',
            'Los planes pausados le van. Los de sprint, le dejan a medias.',
            'En una crisis es agua. En una fiesta, a veces también, y hay que sacudir un poco.',
            'No hace falta gritar para que oiga. Hace falta no confundir calma con que da igual.',
        ],
        'nervioso' => [
            'Se le ve el motor. La pierna, el vaso, la frase a medias.',
            'El cuerpo avisa antes que la boca. Si aprendes el código, llegas a tiempo.',
            'No para. Aunque esté en una silla. El descanso es otra cosa, y cuesta.',
            'Un sitio nuevo le sube el volumen interno. Un sitio conocido, lo baja.',
            'Hablar le ayuda. Callar del todo, a veces lo pone peor.',
            'No hace falta decir que se note. Se nota. Mejor un plan claro que un "relájate".',
            'Celestine: un rato al aire o un café sencillo suelen bajar más que un discurso.',
        ],
        'caotico' => [
            'El orden le parece una sugerencia. Llega, pero no por el camino del mapa.',
            'Improvisa. A veces sale bien. El resto es anécdota, o incendio.',
            'Las llaves, el recado, la hora: viven en un cajón mental con goteras.',
            'Un cambio de plan le sienta bien. A quien planea, le puede sentar mal.',
            'La mesa acaba llena. La conversación, también. El hilo, a ratos, se pierde.',
            'Pedir puntualidad estricta es pedir un milagro menor. Un margen, civilización.',
            'No es desprecio: es que el día se le desordena solo. Quien se apunta, se apunta a eso.',
        ],
    ],
    'gustos' => [
        'cine_terror' => [
            'El terror le pone de un humor extrañamente bueno. No preguntes.',
            'Si hay sangre de atrezzo, se queda. Si hay comedia romántica, negocia.',
            'Sale de la sala comentando el susto. El susto era el plan.',
            'Una noche de miedo en casa también vale. Las luces, bajas.',
            'Regalar un póster raro acierta. Elegir "algo suave" por si acaso, menos.',
        ],
        'cine_comedia' => [
            'Quiere reírse en la butaca. El resto es opcional.',
            'Una comedia floja le ofende más que un drama serio. Tiene un punto.',
            'Si nadie se ríe en la sala, se le atraganta la palomita.',
            'Repite las buenas. Cita las frases. El pueblo ya las ha oído.',
            'Propón risa y tienes plan. Propón "cine importante", ya es otra negociación.',
        ],
        'cine_romantico' => [
            'Las de amor le llegan. No lo anuncia con un megáfono, pero se le nota.',
            'No va de postal: es que esas películas le funcionan. Distinto.',
            'Un final previsible le vale si el camino está bien. Si no, se queja con cariño.',
            'En el sofá o en sala: el pañuelo, por si acaso, no es broma.',
            'Burlarse del género le cierra un poco. Verla juntos, abre.',
        ],
        'cine_accion' => [
            'Quiere que pasen cosas. Diálogo de dos horas le parece un atraco.',
            'Explosiones, persecuciones, palomitas. El arte, otro día.',
            'Un estreno de verano le organiza el calendario. El resto, relleno.',
            'Si la persecución está bien, perdona el guion. Si no, no perdona nada.',
            'Propón acción y hay plan. Propón subtítulos densos, prepara debate.',
        ],
        'cine_thriller' => [
            'Le gusta que la trama apriete. Si lo ve venir, se enfada con el guion.',
            'Sale del cine comentando agujeros. Es su forma de querer la película.',
            'Un spoiler de crimen le sienta como un empujón. Anota, anota.',
            'El silencio de la sala, aquí, es parte del juego. El móvil, no.',
            'Recomendar un thriller bueno es un favor. Contar el giro, un delito.',
        ],
        'cine_autor' => [
            'Le tiran las raras. Subtítulos, silencios, finales que no cierran. Su rollo.',
            'Si dices "no la he entendido", se le ilumina el día. Por fin alguien honesto. O un aliado.',
            'Un pase alternativo le parece plan de verdad. Un blockbuster, según el humor.',
            'Habla de planos como otros de goles. Tú decides si te quedas.',
            'No es pose: es que esas películas le dejan pensando. El palomitas, opcional.',
        ],
        'lectura_novela' => [
            'Historias largas. Personajes. Que le dejen vivir en otra parte un rato.',
            'Acaba un libro y necesita un día de duelo. Es oficial.',
            'Un personaje bien hecho le dura más que un cotilleo de pasillo.',
            'Regalar novela es acertar si preguntas antes. Una al azar, riesgo.',
            'Habla de tramas con una seriedad de recado importante.',
        ],
        'lectura_ensayo' => [
            'Prefiere que el libro le explique el mundo, no que le invente uno.',
            'Subraya. Discute con el autor. El autor no se entera; quien lee, sí.',
            'Un dato bien contado le alegra el café. Una teoría floja, le pica.',
            'La ficción, según el día. La no ficción, casi siempre.',
            'Regalar un ensayo bueno es fino. Regalar autoayuda vaga, un tropiezo.',
        ],
        'pasteleria' => [
            'El dulce no es un postre: es una política.',
            'Si hay tarta, hay trato. Si no hay tarta, hay negociación.',
            'Sabe qué día está el hojaldre. Eso, aquí, es poder.',
            'Un cumple sin dulce le parece un trámite. Con dulce, una fiesta.',
            'Regalar algo rico acierta. Decir "mejor no, por la línea", un riesgo innecesario.',
        ],
        'cocina_de_casa' => [
            'Le puede una buena receta de toda la vida más que un menú con espuma.',
            'Si el plato sabe a domingo de pueblo, se rinde.',
            'El guiso bien hecho le cierra el carácter. La novedad por la novedad, no.',
            'Habla de cucharas de palo con respeto. El gadget, según.',
            'Invitar a casa a comer es el plan. El restaurante de moda, otro capítulo.',
        ],
        'mesa_formal' => [
            'Le gusta que la cosa tenga mantel y copas. De vez en cuando, no siempre.',
            'Un restaurante "en condiciones" le sienta como un traje bien cortado.',
            'La reserva, el vaso, el ritmo: forma parte del gusto. No es pose pura.',
            'Un sitio cualquiera le vale un martes. Un sábado, pide un poco más.',
            'Propón mesa puesta y hay ilusión. Propón de pie con servilleta de papel, según el día.',
        ],
        'cafe_en_serio' => [
            'El café le importa. El de máquina de gasolinera es una ofensa personal.',
            'Puede hablar cinco minutos de un grano. Tú decides si te quedas.',
            'Un barista que se esmera le mejora el pueblo. Uno que no, lo empeora.',
            'El café malo se nota en el humor. No es capricho: es el primer trago del día.',
            'Invitar a "un café de verdad" es un plan. Invitar a uno cualquiera, un apaño.',
        ],
        'terrazas' => [
            'Fuera, siempre que se pueda. El interior le sabe a espera del dentista.',
            'Una terraza le arregla el carácter. El aire, no el menú.',
            'Si hay sol de invierno, aparece. Si hay cristal cerrado, negocia.',
            'El café, la copa, la merienda: mejor con calle. El techo, para el mal tiempo.',
            'Pedir mesa fuera no es manía. Es que dentro se le encoge el día.',
        ],
        'sitios_con_ruido' => [
            'Le sienta bien el jaleo. Pensar, ya pensará mañana.',
            'Si el sitio está muerto, se apaga un poco también.',
            'El volumen alto le pone en su sitio. El murmullo de biblioteca, otro día.',
            'Bar, karaoke, un bolo: el ruido es parte del plan, no un accidente.',
            'Un local callado le parece sala de espera. Uno vivo, domingo.',
        ],
        'sitios_en_silencio' => [
            'Necesita sitios donde no le griten el café. No es pedantería: es supervivencia.',
            'El silencio le trabaja a favor. El resto del pueblo, a veces no.',
            'Una mesa de rincón le vale más que una barra llena.',
            'Biblioteca, spa, mirador: el volumen bajo es el lujo.',
            'Propón un sitio quieto y hay alivio. Propón un local a gritos, hay veto.',
        ],
        'luces_bajas' => [
            'Le van los sitios oscuritos. No es misterio: es que se relaja.',
            'Con luz de oficina se encoge. Con luz de bar, aparece.',
            'La barra del fondo es territorio. El fluorescente, un enemigo menor.',
            'De noche, con poca luz, habla mejor. De día, en un recinto blanco, menos.',
            'Un plan de luces bajas le sienta. Uno de centro comercial a las doce, otro humor.',
        ],
        'competir' => [
            'Le gusta ganar. Y que se note, un poco.',
            'Un marcador le pone en modo serio. Luego dice que era broma.',
            'Arcade, bingo, un partido, una caja de mesa: hay palmarés.',
            'La revancha es el postre. Quien se niega, corta el hilo.',
            'Un plan "a ver quién" le enciende. Un plan sin puntuación, le sabe a poco.',
        ],
        'coleccionar_piezas' => [
            'No compra por comprar: busca "la" cosa. La reconoce al vuelo.',
            'Un hallazgo le da para una semana de conversación. Prepárate.',
            'La vitrina tiene ley. Tocar, con permiso. Mover, ni se discute.',
            'Ropa, libros, una figura rara: el objeto importa más que la marca.',
            'Regalar una pieza cierta es un acierto grande. Una parecida, un riesgo.',
        ],
        'ropa_atrevida' => [
            'Le gusta que la ropa diga algo. Aunque sea "mira".',
            'Lo discreto le parece un desperdicio. No siempre, pero a menudo.',
            'Probarse algo loco es plan. Salir con ello, según el valor del día.',
            'Un cumplido sobre el conjunto le dura. Ignorarlo, también se nota.',
            'La tienda, aquí, es escenario. El aparador, el primer acto.',
        ],
        'ropa_comoda' => [
            'Si no se puede sentar, no se lo pone. Fin del comunicado.',
            'La elegancia empieza por no estar sufriendo. El resto es adorno.',
            'Un zapato que vive le parece lujo. Uno que aprieta, teatro inútil.',
            'El parque, el sofá, un recado: pide tela que perdone el día.',
            'Regalar algo suave acierta. Regalar un martirio bonito, menos.',
        ],
        'agua_caliente' => [
            'El agua caliente le arregla más que un consejo bienintencionado.',
            'Si el cuerpo pide tregua, no pide fiesta: pide vapor y que cierren la puerta.',
            'Un circuito, un baño, una ducha larga: es plan, no relleno.',
            'El spa le entiende. El ruido de la calle, a la salida.',
            'Regalar un rato de agua caliente es fino. Llenar la agenda ese mismo día, no.',
        ],
        'sudar' => [
            'Si no suda, considera que no ha hecho nada. Es una teoría discutible y suya.',
            'El esfuerzo le pone de buen humor. El sofá, a veces al revés.',
            'Correr, pesas, baile, bici: el cuerpo pide trabajo de verdad.',
            'Después, la ducha es sagrada. El plan siguiente, según las piernas.',
            'Un plan suave le sabe a poco. Uno que deje la camiseta lista, encaja.',
        ],
        'atardeceres' => [
            'El atardecer le funciona. No hace falta violín. Con el cielo basta.',
            'Se queda mirando la luz como quien mira un recado importante.',
            'El mirador, el parque, una ventana: el sitio es la hora, no el anuncio.',
            'Fotografiar sí. Convertirlo en escena de película, no hace falta.',
            'Quedar a esa hora es un plan sencillo y bueno. Vestirlo de declaración, otro recado.',
        ],
        'documentales' => [
            'Prefiere que le cuenten algo que existe. La ficción, según el día.',
            'Un buen documental le da tema para tres cafés. Aviso a la mesa.',
            'Sale recomendando rarezas. Tú decides si apuntas o sonríes.',
            'El sofá, aquí, es aula. El palomitas, opcional.',
            'Regalar un documental que encaje es fino. Uno genérico de "cultura", un apaño.',
        ],
        'chisme_sano' => [
            'Le gusta estar al tanto. No es oficio sucio: es que el pueblo es su serie.',
            'Pregunta. Se entera. No siempre reparte lo que sabe. Eso ya es carácter.',
            'Un café, el bingo, la barra: el serial se actualiza solo.',
            'El chisme con tacto le parece convivencia. El que hace daño, le cierra.',
            'Contar algo de pasada abre puerta. Pedir sangre, la cierra.',
        ],
        'escenario' => [
            'Le tira subirse un rato. El pánico y el gusto van de la mano.',
            'Un micro le cambia la postura. Luego vuelve a ser quien era. O no.',
            'Karaoke, un bolo, una broma al aire: el palco le pica de forma buena.',
            'No siempre sale bien. Sale. Eso, para esta persona, cuenta.',
            'Sacar al escenario funciona si hay ganas. Obligar, apaga la gana.',
        ],
        'naturaleza_sin_gente' => [
            'La naturaleza le gusta más si no hay picnic de treinta. El pájaro, sí; el bluetooth, no.',
            'Se aleja un poco y se le ve más fácil. O eso parece.',
            'Un sendero casi vacío le arregla el día. Uno de procesión, lo empeora.',
            'El parque a primera hora es oro. El parque en feria, otra conversación.',
            'Propón campo y silencio y hay sí. Propón merienda masiva, hay pero.',
        ],
        'grupos_grandes' => [
            'Cuanta más gente, mejor. Se enciende. Es agotador y contagioso.',
            'Un plan de dos le sabe a poco. Un plan de doce, a domingo.',
            'Bingo, fiesta, un partido, una asociación: el rebaño, aquí, es combustible.',
            'Se le ve la sonrisa cuando la mesa no cabe. Se le ve también el cansancio después.',
            'Apuntar a más gente suele alegrar. Dejar el plan en dos, según el día, sabe a poco.',
        ],
    ],
    'rechazos' => [
        'act_bailar' => [
            'La música le puede. Bailar, no. Distinción importante, Celestine.',
            'En la pista se queda de estatua con copa. No es timidez: es veto.',
            'Sacar a bailar es mala idea. La barra, en cambio, funciona.',
            'El cuerpo no se apunta. El oído, sí. No lo mezcles.',
            'Una discoteca con pista obligatoria le cierra la noche. Un bar con música, no.',
        ],
        'act_cantar_en_publico' => [
            'Cantar en público no entra. Mirar, a lo mejor. Subirse, no.',
            'Un micro ajeno ya le parece demasiado. El propio, ni se discute.',
            'El karaoke como público le vale. El karaoke como turno, no.',
            'Pedir un dueto es un empujón. Un empujón que no ayuda.',
            'Hay otras formas de noche. Esta, concretamente, está vetada.',
        ],
        'act_sudar_en_publico' => [
            'El esfuerzo le parece bien. El espejo del gimnasio, no tanto.',
            'Sudar sí. Hacerlo con un patio de butacas, ya es otro deporte.',
            'Prefiere el esfuerzo sin testigos. El sudor, que se quede entre cuatro paredes conocidas.',
            'Una clase llena le pone el cuello tieso. No es metáfora.',
            'Correr al alba, vale. Una sala con veinte pares de ojos, ya es otra conversación.',
        ],
        'act_ir_de_tiendas' => [
            'Los escaparates le cansan. Entrar a "mirar" le parece una trampa, sea ropa, libros o cajas raras.',
            'Regalar un plan de tiendas es un acto de fe. O de maldad. Da igual el mostrador.',
            'Un recado concreto, vale. "Vamos a ver qué hay", le cierra el carácter.',
            'Pasillos, colas, probarse por probarse: le sienta como una espera del médico.',
            'La tienda le parece un laberinto con precio. Prefiere que le digan qué hace falta y ya.',
        ],
        'act_competir' => [
            'Jugar le gusta. Que haya un ganador, le amarga la boca.',
            'Si el plan es "a ver quién gana", cuenta con una baja.',
            'Un torneo le quita el gusto al juego. Una partida sin palmarés, se queda.',
            'El marcador le pone tenso el café de después. Mejor no hay marcador.',
            'Arcade, bingo, un partido: si huele a ranking, se echa atrás.',
        ],
        'ctx_perder_en_publico' => [
            'Lleva fatal perder. Sobre todo si hay testigos. Anota, anota.',
            'La derrota le deja de un humor que no merece un café después.',
            'Un cartón fallido con corro alrededor le sienta como un empujón.',
            'Jugar en casa, vale. Jugar con público y perder, ya es otro deporte.',
            'La partida pública tiene un coste. El pueblo no siempre lo ve.',
        ],
        'ctx_biblioteca_habitat' => [
            'Lee, sí. Convertir la biblioteca en salón, no. Hay una línea.',
            'Un rato entre estantes le vale. Una tarde entera le parece encierro.',
            'El libro en casa o en el café. El edificio como hábitat, no.',
            'Un plan que sea "nos vemos en la biblioteca y nos quedamos" le cierra.',
            'Leer no obliga a vivir entre lomos. Celestine, no lo mezcles.',
        ],
        'ctx_multitud' => [
            'La gente, bien. El rebaño, mal. No es lo mismo y se enfada si lo mezclas.',
            'A partir de cierto número de cuerpos, se apaga. No es un fallo: es un límite.',
            'Una fiesta mayor le sienta como un empujón. Un corro pequeño, bien.',
            'La discoteca llena, el bingo a tope: el aforo le gana al plan.',
            'Más gente no es más alegría. A partir de un punto, es menos persona.',
        ],
        'ctx_silencio_sepulcral' => [
            'El silencio total le pone de los nervios. Un murmullo, bien. Una tumba, no.',
            'En la biblioteca se le escapa la tos. Siempre. Es una maldición menor.',
            'El spa callado le incomoda si nadie respira. Un hilo de voz, salva.',
            'Un "shhh" ajeno le sube el pulso. El rumor de cafetería, le calma.',
            'No pide jaleo. Pide que el silencio no parezca un examen.',
        ],
        'ctx_que_te_toquen' => [
            'El spa le va… hasta que alguien le pone las manos. Entonces, no.',
            'El contacto no solicitado le cierra el día. Incluido el bienintencionado.',
            'Un masaje ofertado es un no educado. Insistir, un no menos educado.',
            'La aglomeración que pega codo con codo le sienta mal. El espacio, bien.',
            'Preguntar antes vale. Dar por hecho el abrazo o el apretón, no.',
        ],
        'ctx_postal_romantica' => [
            'El mirador le gusta. El paquete "atardecer + violín + ahora os besáis", no.',
            'Si el plan parece un anuncio, se ríe. O se va. Según el día.',
            'La postal le saca de quicio. La vista, no. Distinción importante.',
            'Un picnic sencillo vale. Un picnic con playlist de boda, ya es teatro.',
            'Celestine: no conviertas un sitio bonito en declaración obligatoria.',
        ],
        'ctx_alcohol' => [
            'El bar le puede. La copa, no. Hay zumo y hay conversación. No es un drama.',
            'No bebe. No hace falta un discurso. Un tono de lástima, sí sería un drama.',
            'Una ronda obligatoria le pone contra la pared. Una alternativa, le deja en paz.',
            'La discoteca con copa por medio, peor. El bar con un refresco, encaja.',
            'Insistir "una no hace daño" hace daño. El veto es el veto.',
        ],
        'ctx_improvisar_plan' => [
            'Lo de "vente ahora" le sienta como un empujón. Avisa con tiempo.',
            'Improvisar pone de mal humor. No es sequedad: es que se organiza.',
            'Una quedada sorpresa le descoloca el día. Una quedada avisada, le abre.',
            'El calendario no es pose. Es cómo llega a los sitios de buen humor.',
            'Celestine: si el plan sale hoy, dilo esta mañana. Mejor, ayer.',
        ],
        'ctx_mostrador_eterno' => [
            'Un café, sí. Convertir la cafetería en oficina vitalicia, no. Hay sillas en casa.',
            'Le gusta el café. No le gusta que el plan sea "la de siempre, dos horas".',
            'La mesa de siempre le cansa si es la única opción. Variar, ayuda.',
            'Un rato, vale. Un turno completo de mostrador, le parece encierro con taza.',
            'Quedar a café funciona. Quedar a habitar la cafetería, no.',
        ],
        'ctx_comer_fuera' => [
            'Cocina. Que le pongan la mesa en un restaurante le parece un robo con mantel.',
            'Salir a comer le cansa. El de casa le sabe a domingo; el de fuera, a trámite.',
            'Una reserva "no, gracias" no es sequedad: es que el puchero gana.',
            'El restaurante le sienta a trámite y a precio. La cocina propia, a plan.',
            'Invitar a casa acierta. Invitar a un local por sistema, menos.',
        ],
        'ctx_sala_a_oscuras' => [
            'Las películas le gustan. La sala, con extraños tosiendo, no. El sofá gana.',
            'Ir al cine le parece un palomitas a precio de alquiler. Ver, vería.',
            'Unas entradas de regalo son un riesgo. Un maratón en casa, un acierto.',
            'La oscuridad ajena le distrae. La de casa, no.',
            'Cine sí. Destino sala, no. Celestine, no lo mezcles.',
        ],
        'ctx_parque_lleno' => [
            'El parque le va. El parque en masa, con bluetooth y tupperware de treinta, no.',
            'Pasear sí. Hacer cola para un banco, ya es otra afición que no tiene.',
            'Un domingo de multitud le quita el sitio. Un lunes temprano, se lo devuelve.',
            'El picnic íntimo vale. El picnic de feria, le cierra el carácter.',
            'Naturaleza sí. Procesión en el césped, no. Hay diferencia y se enfada si no se ve.',
        ],
    ],
];
