<?php
declare(strict_types=1);

/**
 * Rechazos que NO son simplemente “la afición en negativo”.
 * Destinos: se rechazan por id de lugar (lug_*), sin duplicar el catálogo de edificios.
 * Aficiones/gustos: polaridad en el perfil, no entradas nuevas aquí.
 */
return [
    [
        'id' => 'act_bailar',
        'tipo' => 'actividad',
        'etiqueta' => 'Bailar',
        'contra' => ['baile'],
        'lugar_ids' => ['lug_discoteca'],
        'usos' => ['lugares', 'planes', 'celestine', 'descubrimientos'],
        'descubrimientos' => [
            'La música le puede. Bailar, no. Distinción importante, Celestine.',
            'En la pista se queda de estatua con copa. No es timidez: es veto.',
        ],
        'hooks' => ['sacar_a_bailar_mal_idea'],
    ],
    [
        'id' => 'act_cantar_en_publico',
        'tipo' => 'actividad',
        'etiqueta' => 'Cantar en público',
        'contra' => ['karaoke'],
        'lugar_ids' => ['lug_karaoke'],
        'usos' => ['lugares', 'planes', 'descubrimientos'],
        'descubrimientos' => [
            'Cantar en público no entra. Mirar, a lo mejor. Subirse, no.',
            'Un micro ajeno ya le parece demasiado. El propio, ni se discute.',
        ],
        'hooks' => ['micro_abierto'],
    ],
    [
        'id' => 'act_sudar_en_publico',
        'tipo' => 'actividad',
        'etiqueta' => 'Sudar con público',
        'contra' => ['gimnasio', 'baile', 'correr'],
        'lugar_ids' => ['lug_gimnasio', 'lug_discoteca'],
        'usos' => ['lugares', 'rutinas', 'descubrimientos'],
        'descubrimientos' => [
            'El esfuerzo le parece bien. El espejo del gimnasio, no tanto.',
            'Sudar sí. Hacerlo con un patio de butacas, ya es otro deporte.',
        ],
        'hooks' => ['clase_colectiva'],
    ],
    [
        'id' => 'act_ir_de_tiendas',
        'tipo' => 'actividad',
        'etiqueta' => 'Ir de tiendas',
        'contra' => ['moda'],
        'lugar_ids' => ['lug_tienda'],
        'usos' => ['lugares', 'planes', 'regalos'],
        'descubrimientos' => [
            'Los escaparates le cansan. Entrar a “mirar” le parece una trampa.',
            'Regalarle un plan de tiendas es un acto de fe. O de maldad.',
        ],
        'hooks' => ['rebajas'],
    ],
    [
        'id' => 'act_competir',
        'tipo' => 'actividad',
        'etiqueta' => 'Competir',
        'contra' => ['competir', 'videojuegos_competitivo', 'deporte_equipo'],
        'lugar_ids' => ['lug_arcade', 'lug_bingo'],
        'usos' => ['planes', 'compatibilidad', 'descubrimientos'],
        'descubrimientos' => [
            'Jugar le gusta. Que haya un ganador, le amarga la boca.',
            'Si el plan es “a ver quién gana”, cuenta con una baja.',
        ],
        'hooks' => ['torneo'],
    ],
    [
        'id' => 'ctx_perder_en_publico',
        'tipo' => 'contexto',
        'etiqueta' => 'Perder delante de gente',
        'contra' => ['competir'],
        'lugar_ids' => ['lug_arcade', 'lug_bingo', 'lug_karaoke'],
        'usos' => ['eventos', 'cotilleo', 'compatibilidad', 'descubrimientos'],
        'descubrimientos' => [
            'Lleva fatal perder. Sobre todo si hay testigos. Anota, anota.',
            'La derrota le deja de un humor que no merece un café después.',
        ],
        'hooks' => ['carton_fallido', 'partida_publica'],
    ],
    [
        'id' => 'ctx_biblioteca_habitat',
        'tipo' => 'contexto',
        'etiqueta' => 'Vivir en la biblioteca',
        'contra' => ['leer'],
        'lugar_ids' => ['lug_biblioteca'],
        'usos' => ['lugares', 'rutinas', 'celestine'],
        'descubrimientos' => [
            'Lee, sí. Convertir la biblioteca en salón, no. Hay una línea.',
            'Un rato entre estantes le vale. Una tarde entera le parece encierro.',
        ],
        'hooks' => ['plan_solo_biblioteca'],
        'nota' => 'Sirve para lectora que no quiere el destino como hábitat.',
    ],
    [
        'id' => 'ctx_multitud',
        'tipo' => 'contexto',
        'etiqueta' => 'Muchísima gente',
        'contra' => ['grupos_grandes', 'fiesta'],
        'lugar_ids' => ['lug_discoteca', 'lug_bingo'],
        'usos' => ['lugares', 'planes', 'preferencias_sociales'],
        'descubrimientos' => [
            'La gente, bien. El rebaño, mal. No es lo mismo y se enfada si lo mezclas.',
            'A partir de cierto número de cuerpos, se apaga. No es un fallo: es un límite.',
        ],
        'hooks' => ['fiesta_mayor'],
    ],
    [
        'id' => 'ctx_silencio_sepulcral',
        'tipo' => 'contexto',
        'etiqueta' => 'Silencio de museo',
        'contra' => ['sitios_en_silencio'],
        'lugar_ids' => ['lug_biblioteca', 'lug_spa'],
        'usos' => ['lugares', 'planes'],
        'descubrimientos' => [
            'El silencio total le pone nerviosa. Un murmullo, bien. Una tumba, no.',
            'En la biblioteca se le escapa la tos. Siempre. Es una maldición menor.',
        ],
        'hooks' => ['shhh'],
    ],
    [
        'id' => 'ctx_que_te_toquen',
        'tipo' => 'contexto',
        'etiqueta' => 'Que le toquen (masajes, aglomeración)',
        'contra' => ['spa'],
        'lugar_ids' => ['lug_spa', 'lug_discoteca'],
        'usos' => ['lugares', 'planes', 'afecto_estilo'],
        'descubrimientos' => [
            'El spa le va… hasta que alguien le pone las manos. Entonces, no.',
            'El contacto no solicitado le cierra el día. Incluido el bienintencionado.',
        ],
        'hooks' => ['masaje_ofertado'],
    ],
    [
        'id' => 'ctx_postal_romantica',
        'tipo' => 'contexto',
        'etiqueta' => 'Romanticismo de postal',
        'contra' => ['cine_romantico', 'atardeceres'],
        'lugar_ids' => ['lug_mirador', 'lug_picnic'],
        'usos' => ['planes', 'celestine', 'cotilleo'],
        'descubrimientos' => [
            'El mirador le gusta. El paquete “atardecer + violín + ahora os besáis”, no.',
            'Si el plan parece un anuncio, se ríe. O se va. Según el día.',
        ],
        'hooks' => ['plan_de_pelicula'],
        'nota' => 'Evita romántico = mirador.',
    ],
    [
        'id' => 'ctx_alcohol',
        'tipo' => 'contexto',
        'etiqueta' => 'Alcohol',
        'contra' => ['copas'],
        'lugar_ids' => ['lug_bar', 'lug_discoteca'],
        'usos' => ['lugares', 'planes', 'regalos'],
        'descubrimientos' => [
            'El bar le puede. La copa, no. Hay zumo y hay conversación. No es un drama.',
            'No bebe. No hace falta un discurso. Un tono de “pobrecita”, sí sería un drama.',
        ],
        'hooks' => ['ronda_obligatoria'],
    ],
    [
        'id' => 'ctx_improvisar_plan',
        'tipo' => 'contexto',
        'etiqueta' => 'Planes de última hora',
        'contra' => [],
        'lugar_ids' => [],
        'usos' => ['celestine', 'planes', 'rutinas'],
        'descubrimientos' => [
            'Lo de “vente ahora” le sienta como un empujón. Avisa con tiempo.',
            'Improvisar pone de mal humor. No es sequedad: es que se organiza.',
        ],
        'hooks' => ['quedada_sorpresa'],
    ],
    [
        'id' => 'ctx_mostrador_eterno',
        'tipo' => 'contexto',
        'etiqueta' => 'La cafetería como despacho',
        'contra' => ['cafe_con_gente'],
        'lugar_ids' => ['lug_cafeteria'],
        'usos' => ['lugares', 'planes', 'celestine'],
        'descubrimientos' => [
            'Un café, sí. Convertir la cafetería en oficina vitalicia, no. Hay sillas en casa.',
            'Le gusta el café. No le gusta que el plan sea “la de siempre, dos horas”.',
        ],
        'hooks' => ['mesa_de_siempre'],
    ],
    [
        'id' => 'ctx_comer_fuera',
        'tipo' => 'contexto',
        'etiqueta' => 'Comer fuera',
        'contra' => ['restaurantes'],
        'lugar_ids' => ['lug_restaurante'],
        'usos' => ['lugares', 'planes', 'regalos'],
        'descubrimientos' => [
            'Cocina. Que le pongan la mesa en un restaurante le parece un robo con mantel.',
            'Salir a comer le cansa. El de casa le sabe a domingo; el de fuera, a trámite.',
        ],
        'hooks' => ['reserva_no_gracias'],
    ],
    [
        'id' => 'ctx_sala_a_oscuras',
        'tipo' => 'contexto',
        'etiqueta' => 'La sala de cine',
        'contra' => ['cine_sala'],
        'lugar_ids' => ['lug_cine'],
        'usos' => ['lugares', 'planes'],
        'descubrimientos' => [
            'Las películas le gustan. La sala, con extraños tosiendo, no. El sofá gana.',
            'Ir al cine le parece un palomitas a precio de alquiler. Ver, vería.',
        ],
        'hooks' => ['entradas_regalo'],
        'nota' => 'Pareja de ver_en_casa: cine sí, destino no.',
    ],
    [
        'id' => 'ctx_parque_lleno',
        'tipo' => 'contexto',
        'etiqueta' => 'El parque cuando hay feria',
        'contra' => ['pasear', 'picnic'],
        'lugar_ids' => ['lug_parque', 'lug_picnic'],
        'usos' => ['lugares', 'rutinas'],
        'descubrimientos' => [
            'El parque le va. El parque en masa, con bluetooth y tupperware de treinta, no.',
            'Pasear sí. Hacer cola para un banco, ya es otra afición que no tiene.',
        ],
        'hooks' => ['domingo_multitud'],
    ],
];
